# -*- coding: utf-8 -*-
"""Personal Assignment ATCA - LAB COSC6042036.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqmKrQ-BD5M9cVM9k0XnG9ArI5UoPoZG
"""

# Import library
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

# 1. Generate data
X, y_true = make_blobs (
    n_samples=300,
    centers=3,
    random_state=42
)

# ubah ke DataFrame biar rapi
df = pd.DataFrame(X, columns=["Feature 1", "Feature 2"])

# 2. Clustering dengan KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
df["KMeans Cluster"] = kmeans.fit_predict(X)

# 3. Clustering dengan Gaussian Mixture Model
gmm = GaussianMixture(n_components=3, random_state=42)
df["GMM Cluster"] = gmm.fit_predict(X)

# 4. Visualisasi hasil clustering
plt.figure(figsize=(12, 5))

# Plot Kmeans
plt.subplot(1, 2, 1)
plt.scatter(df["Feature 1"], df["Feature 2"], c=df["KMeans Cluster"])
plt.title("Hasil Clustering dengan Kmeans")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

# Plot GMM
plt.subplot(1, 2 ,2)
plt.scatter(df["Feature 1"], df["Feature 2"], c=df["GMM Cluster"])
plt.title("Hasil Clustering dengan Gaussian Mixture Model")
plt.xlabel("Feature 1")
plt.ylabel("Featuer 2")

plt.show()

# Tampilkan beberapa data
df.head()